version: "3.9"
services: 
    bookapi:
        container_name: book-manager
        build:
          context: ../.
          dockerfile: docker/Dockerfile
        ports:
            - "5276:80"
        depends_on:
          - mssql

    mssql:
      container_name: mssql
      hostname: mssql
      image: "mcr.microsoft.com/mssql/server"
      user: root
      ports:
        - "1433:1433"
      environment:
        SA_PASSWORD: ${MSSQL_ADMIN_PASSWORD}
        ACCEPT_EULA: "Y"
      volumes:
        - /var/opt/mssql/data
networks:
  default:
    name: net-book-manager
